### ISSUE TITLE
Npm windows 10 : TypeError: res.getBody is not a function

### ISSUE THREAD

**Issue by bdelattre-decathlon** [soprasteria/sonar-report#100]
Hello all,

When trying to generate a report, I get this error : 

`C:\Users\Benjamin>sonar-report --sonarurl="https://sonarcloud.io" --sonartoken=xxx --sonarorganization=xxx --project=xxx --sinceleakperiod=true --allbugs=true`

```
No proxy configuration detected
sonarqube version: 8.0.0.27634
(node:13560) UnhandledPromiseRejectionWarning: TypeError: res.getBody is not a function at  C:\Users\Benjamin\AppData\Roaming\npm\node_modules\sonar-report\index.js:242:33 at processTicksAndRejections (internal/process/task_queues.js:97:5) 
(node:13560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)   
(node:13560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I work on windows 10, Node version v12.22.11, Npm version 6.14.16

Which package do I miss ? Could you please help me ?

**Comment by thecampagnards** [comment]
Ah my bad I didn't release the fixes
I will do it when I will be on my computer

**Comment by thecampagnards** [comment]
I publish the 2.4.0 it should fix the problem
